# Generated by Django 6.0.4 on 2026-05-03 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('professional_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('specialty', models.CharField(max_length=255, verbose_name='Especialidad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('bio', models.TextField(blank=True, verbose_name='Descripción profesional')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('working_days', models.CharField(help_text='Ej: lunes,martes,miercoles', max_length=255, verbose_name='Días de atención')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('appointment_duration_minutes', models.IntegerField(default=30, verbose_name='Duración del turno (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('health_insurance', models.CharField(blank=True, max_length=255, verbose_name='Obra social')),
                ('health_insurance_plan', models.CharField(blank=True, max_length=255, verbose_name='Plan')),
                ('health_insurance_number', models.CharField(blank=True, max_length=255, verbose_name='Nro. afiliado')),
                ('clinical_notes', models.TextField(blank=True, verbose_name='Notas clínicas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='core.professional')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'unique_together': {('professional', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_date', models.DateField(verbose_name='Fecha')),
                ('appointment_time', models.TimeField(verbose_name='Hora')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('completed', 'Completado')], default='scheduled', max_length=50, verbose_name='Estado')),
                ('source', models.CharField(choices=[('online', 'Online'), ('manual', 'Manual'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('phone', 'Teléfono')], default='online', max_length=50, verbose_name='Origen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.professional')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['appointment_date', 'appointment_time'],
                'unique_together': {('professional', 'appointment_date', 'appointment_time')},
            },
        ),
    ]
