# Generated by Django 6.0.4 on 2026-05-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='accepts_insurance',
            field=models.BooleanField(default=False, verbose_name='Acepta obra social'),
        ),
        migrations.AddField(
            model_name='professional',
            name='accepts_private',
            field=models.BooleanField(default=True, verbose_name='Acepta particular'),
        ),
        migrations.AddField(
            model_name='professional',
            name='attention_mode',
            field=models.CharField(blank=True, help_text='Ej: Presencial, Online, Presencial y online', max_length=100, verbose_name='Modalidad de atención'),
        ),
        migrations.AddField(
            model_name='professional',
            name='common_reasons',
            field=models.TextField(blank=True, help_text='Separados por coma. Ej: Ansiedad, Estrés, Autoestima', verbose_name='Motivos frecuentes de consulta'),
        ),
        migrations.AddField(
            model_name='professional',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='professionals/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='professional',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, verbose_name='Frase de valor'),
        ),
    ]
