# Generated by Django 6.0.4 on 2026-05-07 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_professional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='mission',
            field=models.TextField(blank=True, help_text='Frase destacada que aparece en la landing como tarjeta azul.', verbose_name='Misión / Filosofía'),
        ),
        migrations.CreateModel(
            name='LandingCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='workspace_premium', help_text='Nombre de Material Symbol. Ej: school, workspace_premium, clinical_notes, verified', max_length=50, verbose_name='Icono Material')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Institución / detalle')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_credentials', to='core.professional')),
            ],
            options={
                'verbose_name': 'Credencial',
                'verbose_name_plural': 'Landing — Credenciales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='medical_services', help_text='Nombre de Material Symbol. Ej: monitor_heart, medical_services, video_chat', max_length=50, verbose_name='Icono Material')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_services', to='core.professional')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Landing — Servicios',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Ej: 15+, 10k+, 4.9, 24', max_length=50, verbose_name='Valor')),
                ('label', models.CharField(help_text='Ej: Años de experiencia', max_length=100, verbose_name='Etiqueta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_stats', to='core.professional')),
            ],
            options={
                'verbose_name': 'Estadística de landing',
                'verbose_name_plural': 'Landing — Estadísticas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='Texto del testimonio')),
                ('author_name', models.CharField(max_length=100, verbose_name='Nombre del autor')),
                ('author_meta', models.CharField(blank=True, help_text='Ej: Paciente desde 2021', max_length=100, verbose_name='Detalle')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Estrellas (0-5)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_testimonials', to='core.professional')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Landing — Testimonios',
                'ordering': ['order'],
            },
        ),
    ]
