# Generated by Django 6.0.4 on 2026-05-07 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_professional_mission_landingcredential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='show_contact',
            field=models.BooleanField(default=True, verbose_name='Mostrar sección de contacto'),
        ),
        migrations.AddField(
            model_name='professional',
            name='show_credentials',
            field=models.BooleanField(default=True, verbose_name='Mostrar credenciales'),
        ),
        migrations.AddField(
            model_name='professional',
            name='show_mission',
            field=models.BooleanField(default=True, verbose_name='Mostrar misión'),
        ),
        migrations.AddField(
            model_name='professional',
            name='show_services',
            field=models.BooleanField(default=True, verbose_name='Mostrar servicios'),
        ),
        migrations.AddField(
            model_name='professional',
            name='show_stats',
            field=models.BooleanField(default=True, verbose_name='Mostrar estadísticas'),
        ),
        migrations.AddField(
            model_name='professional',
            name='show_testimonials',
            field=models.BooleanField(default=True, verbose_name='Mostrar testimonios'),
        ),
        migrations.AddField(
            model_name='professional',
            name='theme_primary',
            field=models.CharField(default='#004ac6', help_text='Color de CTAs, links y tarjeta de misión.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'Color en formato hex. Ej: #3B82F6')], verbose_name='Color principal'),
        ),
    ]
