# Generated by Django 6.0.4 on 2026-05-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_professional_show_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingtestimonial',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Testimonio', 'verbose_name_plural': 'Landing — Testimonios'},
        ),
        migrations.AddField(
            model_name='landingtestimonial',
            name='appointment',
            field=models.OneToOneField(blank=True, help_text='Si vino del flujo post-turno, queda atado al turno (1 reseña por turno).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial', to='core.appointment'),
        ),
        migrations.AddField(
            model_name='landingtestimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='landingtestimonial',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Las reseñas creadas vía link público arrancan en False hasta que el profesional las aprueba.', verbose_name='Aprobado'),
        ),
        migrations.AddField(
            model_name='professional',
            name='show_map',
            field=models.BooleanField(default=True, help_text='Solo se renderiza si además hay una dirección cargada.', verbose_name='Mostrar mapa de ubicación'),
        ),
    ]
