# Generated by Django 6.0.4 on 2026-05-11 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_professional_theme_primary_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='vertical',
            field=models.CharField(blank=True, choices=[('salud', 'Salud'), ('legal', 'Legal'), ('contable', 'Contable / financiero'), ('coaching', 'Coaching / consultoría'), ('creativos', 'Servicios creativos y técnicos'), ('bienestar', 'Bienestar')], default='', help_text='Categoría de servicio. Si se selecciona, define el tint de acento de la landing y la OG image.', max_length=20, verbose_name='Vertical'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='theme_primary',
            field=models.CharField(default='#0047ab', help_text='Color de CTAs, links y tarjeta de misión. Si dejás vertical seleccionada y este campo en cobalto (#0047ab), el accent toma el tint del vertical.', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'Color en formato hex. Ej: #0047ab')], verbose_name='Color principal'),
        ),
    ]
