# Generated by Django 6.0.4 on 2026-05-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_professional_vertical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_url',
            field=models.URLField(blank=True, default='', help_text='Solo se completa cuando el turno es online.', verbose_name='Link de videollamada'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mode',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online (videollamada)')], default='presencial', help_text='Presencial o videollamada. Si es online, se genera un link de Jitsi automáticamente.', max_length=20, verbose_name='Modalidad'),
        ),
    ]
