# Generated by Django 6.0.4 on 2026-05-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_backfill_appointment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Notas privadas del profesional sobre este turno. Solo vos las ves.', verbose_name='Notas del turno'),
        ),
    ]
