# Generated by Django 6.0.4 on 2026-05-11 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_appointment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio congelado al momento de la reserva, independiente de cambios posteriores en el servicio.', max_digits=10, null=True, verbose_name='Precio al reservar'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Servicio elegido. Si es null, se trata como consulta general.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.landingservice'),
        ),
        migrations.AddField(
            model_name='landingservice',
            name='is_bookable',
            field=models.BooleanField(default=True, help_text='Si está activo, los pacientes pueden elegir este servicio al reservar. Desactivá para servicios solo informativos (charlas, workshops).', verbose_name='Reservable online'),
        ),
        migrations.AddField(
            model_name='landingservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Si lo dejás vacío, no se muestra precio en la landing.', max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='professional',
            name='currency',
            field=models.CharField(choices=[('ARS', 'ARS — Pesos argentinos'), ('USD', 'USD — Dólares')], default='ARS', help_text='Moneda en la que mostrás los precios de tus servicios.', max_length=3, verbose_name='Moneda'),
        ),
    ]
