# Generated by Django 6.0.4 on 2026-05-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_appointment_price_at_booking_appointment_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='facebook_url',
            field=models.URLField(blank=True, default='', help_text='URL completa de tu página o perfil.', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='professional',
            name='instagram_url',
            field=models.URLField(blank=True, default='', help_text='URL completa de tu perfil. Ej: https://instagram.com/tu-usuario', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='professional',
            name='x_url',
            field=models.URLField(blank=True, default='', help_text='URL completa de tu perfil. Ej: https://x.com/tu-usuario', verbose_name='X (Twitter)'),
        ),
    ]
