# Generated by Django 6.0.4 on 2026-05-14 00:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_professional_facebook_url_professional_instagram_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='role',
            field=models.CharField(choices=[('solo', 'Profesional individual'), ('owner', 'Dueño/a de clínica'), ('member', 'Miembro de clínica')], default='solo', help_text='solo = sin clínica; owner = dueño; member = profesional invitado.', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la clínica/consultora')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Frase de valor')),
                ('bio', models.TextField(blank=True, verbose_name='Descripción')),
                ('mission', models.TextField(blank=True, verbose_name='Misión')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/', verbose_name='Logo')),
                ('theme_primary', models.CharField(default='#0047ab', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'Color en formato hex. Ej: #0047ab')], verbose_name='Color principal')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, default='', verbose_name='Facebook')),
                ('x_url', models.URLField(blank=True, default='', verbose_name='X (Twitter)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clínica / Consultora',
                'verbose_name_plural': 'Clínicas / Consultoras',
            },
        ),
        migrations.AddField(
            model_name='professional',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Si pertenece a una clínica/consultora, su organización. Null = profesional independiente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email del invitado')),
                ('invited_name', models.CharField(blank=True, help_text='Opcional. Se usa solo para el saludo en el email.', max_length=255, verbose_name='Nombre')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_professional', models.ForeignKey(blank=True, help_text='Profesional creado al aceptar la invitación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.professional')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.organization')),
            ],
            options={
                'verbose_name': 'Invitación a clínica',
                'verbose_name_plural': 'Invitaciones a clínica',
                'ordering': ['-created_at'],
            },
        ),
    ]
