# Generated by Django 6.0.4 on 2026-05-14 00:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_professional_role_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('trialing', 'En prueba'), ('past_due', 'Pago vencido'), ('cancelled', 'Cancelada')], default='active', max_length=20)),
                ('mp_preapproval_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Mercado Pago preapproval ID')),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('manually_set', models.BooleanField(default=False, help_text='True cuando el plan fue cambiado a mano desde el admin de operador. Bloquea sobrescritura por webhooks de MP.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
    ]
