from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('pricing/', views.pricing, name='pricing'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('setup/', views.setup, name='setup'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/appointments/new/', views.appointment_new, name='appointment_new'),
    path('dashboard/appointments/<uuid:appointment_id>/', views.appointment_detail, name='appointment_detail'),
    path('dashboard/appointments/<uuid:appointment_id>/status/', views.appointment_status, name='appointment_status'),
    path('dashboard/patients/', views.patient_list, name='patient_list'),
    path('dashboard/patients/new/', views.patient_new, name='patient_new'),
    path('dashboard/patients/<uuid:patient_id>/', views.patient_detail, name='patient_detail'),
    path('dashboard/landing/', views.landing_admin, name='landing_admin'),
    path('dashboard/clinic/setup/', views.clinic_setup, name='clinic_setup'),
    path('dashboard/clinic/', views.clinic_dashboard, name='clinic_dashboard'),
    path('dashboard/clinic/invite/', views.clinic_invite, name='clinic_invite'),
    path('dashboard/clinic/branding/', views.clinic_branding, name='clinic_branding'),
    path('dashboard/clinic/invitations/<uuid:invitation_id>/revoke/', views.clinic_revoke_invitation, name='clinic_revoke_invitation'),
    path('dashboard/clinic/members/<uuid:professional_id>/remove/', views.clinic_remove_member, name='clinic_remove_member'),
    path('p/<slug:slug>/', views.public_landing, name='public_landing'),
    path('p/<slug:slug>/booking/', views.booking, name='booking'),
    path('p/<slug:slug>/review/<str:token>/', views.public_review, name='public_review'),
    path('c/<slug:slug>/', views.clinic_public_landing, name='clinic_public_landing'),
    path('c/join/<str:token>/', views.clinic_join, name='clinic_join'),
    path('operador/', views.operator_home, name='operator_home'),
    path('operador/profesionales/', views.operator_professionals, name='operator_professionals'),
    path('operador/clinicas/', views.operator_organizations, name='operator_organizations'),
    path('operador/turnos/', views.operator_appointments, name='operator_appointments'),
    path('operador/usuario/<int:user_id>/', views.operator_user_detail, name='operator_user_detail'),
    path('operador/usuario/<int:user_id>/toggle-pro/', views.operator_toggle_pro, name='operator_toggle_pro'),
    path('api/patients/search/', views.patient_search_api, name='patient_search_api'),
    path('og/default.png', views.og_default, name='og_default'),
    path('og/p/<slug:slug>.png', views.og_professional, name='og_professional'),
]
